### ISSUE TITLE
`style/body/line-height` is not respected

### ISSUE THREAD

**Issue by figure002** [jelovirt/pdf-generator#105]
**Steps to reproduce**

1. Create a PDF output using a theme file included with DITA-OT (e.g. `dita-ot/docsrc/samples/themes/dita-ot-docs-theme.yaml`)
2. In the theme file change:

```yaml
style:
  body:
    line-height: 1.3
```

to:

```yaml
style:
  body:
    line-height: 2.3
```

3. Create a PDF output using the updated theme file.

**Result**

The line height has not changed in block content (paragraphs, etc.).

**Expected result**

The line height should change accordingly.

**Notes**

I noticed that it does work for

```yaml
style:
  cover-title:
    line-height: 1
```

But it also doesn't work for

```yaml
style:
  h1:
    line-height: 1
```
