### ISSUE TITLE
`style/table/border-*` is not respected

### ISSUE THREAD

**Issue by figure002** [jelovirt/pdf-generator#106]
I have a table as such:

```xml
<table>
<tgroup cols="2">
<colspec colname="COLSPEC0" colwidth="121*"/>
<colspec colname="COLSPEC1" colwidth="76*"/>
<thead>
<row>
<entry colname="COLSPEC0" valign="top">Animal</entry>
<entry colname="COLSPEC1" valign="top">Gestation</entry>
</row>
</thead>
<tbody>
<row>
<entry>Elephant (African and Asian)</entry>
<entry>19-22 months</entry>
</row>
<row>
<entry>Giraffe</entry>
<entry>15 months</entry>
</row>
<row>
<entry>Rhinoceros</entry>
<entry>14-16 months</entry>
</row>
<row>
<entry>Hippopotamus</entry>
<entry>7 1/2 months</entry>
</row>
</tbody>
</tgroup>
</table>
```

And I try to style the table with:

```yaml
style:
  table:
    border-before-style: none
    border-before-width: 1pt
    border-before-color: black
    border-end-style: none
    border-end-width: 1pt
    border-end-color: black
    border-after-style: none
    border-after-width: 1pt
    border-after-color: black
    border-start-style: none
    border-start-width: 1pt
    border-start-color: black
```

But none of these rules seem to have any effect. I can change the values, but the resulting table remains the same; only a black outer border is displayed.
