### ISSUE TITLE
Desugaring broken for `header/border-after`

### ISSUE THREAD

**Issue by figure002** [jelovirt/pdf-generator#107]
Desugaring seems to be broken for:

```yaml
header:
  border-after: dotted 1pt black
```

This works however:

```yaml
header:
  odd:
    border-after: dotted 1pt black
  even:
    border-after: dotted 1pt black
```
