### ISSUE TITLE
Multilanguage support for `content`

### ISSUE THREAD

**Issue by jelovirt** [jelovirt/pdf-generator#51]
Allow `content` keys to define multiple languages, e.g.

```yaml
header:
 content:
    en-US: User Manual
    de-DE: Benutzerhandbuch
```

If language code is not set, the language defaults to empty string.
