### ISSUE TITLE
PDF `--theme`: Border overrides not applied

### ISSUE THREAD

**Issue by infotexture** [jelovirt/pdf-generator#54]
When building PDF output with `--theme`, border overrides are not applied.

For example, if a theme file contains the following entries:

```yaml
style:
  h1:
    border-after: solid 1pt gray
```

The first-level headings still use the default thick black bottom borders from the default PDF2 settings.
