### ISSUE TITLE
PDF `--theme`: Caption styling

### ISSUE THREAD

**Issue by infotexture** [jelovirt/pdf-generator#55]
Currently, [figure](https://github.com/jelovirt/pdf-generator/wiki/Theme#fig) and [table](https://github.com/jelovirt/pdf-generator/wiki/Theme#fig) styling options allow to set `caption-number` & `caption-position`, but there's no apparent way to set font family/style/weight, alignment, etc. for figure/table titles.

If these settings are made on the `fig` key itself, they apply to the entire figure element:

```yaml
style:
  fig:
    color: $brand-color-secondary
    font-style: italic
    font-weight: normal
    text-align: center
```

If the figure contains a code block, the code block text will be centered & italicized too.
