### ISSUE TITLE
PDF `--theme`: Chapter-based caption numbering

### ISSUE THREAD

**Issue by infotexture** [jelovirt/pdf-generator#66]
When using chapter-based numbering for figures & tables per https://github.com/jelovirt/pdf-generator/pull/62, the chapter numbers in captions do not agree with the section numbering in topic titles.

For example, with the following style settings,

```yaml
style:
  h2:
    title-numbering: true
  table:
    caption:
      number: chapter
```

the [Adding plug-ins via the registry](https://www.dita-ot.org/dev/topics/plugins-registry.html) topic from the DITA-OT docs is numbered as §**8.3**, but the table titles are numbered with **30**:

> - Table 30–1: Plug-in version entry structure
> - Table 30–2: Structure for dependency entries
