### ISSUE TITLE
PDF `--theme`: Table header styling

### ISSUE THREAD

**Issue by infotexture** [jelovirt/pdf-generator#67]
Another common customization is to define shaded backgrounds for table header cells defined in `<thead>` elements.

Would be nice if this could be specified in the theme file with a syntax like this:

```yaml
style:
  table:
    header:
      background-color: $brand-color-inverse
      color: $brand-color-secondary
```

This would be useful along with overrides for `common.border` properties per https://github.com/jelovirt/pdf-generator/issues/54#issuecomment-1272102226.

**Comment by infotexture** [comment]
@jelovirt Would it make sense to apply any `table-header` styles from the theme to other table structures like `<choicetable>`, so all tables share common presentation?

I know that's not how it works in PDF2, just thinking this might be an opportunity to simplify things.

**Comment by infotexture** [comment]
Tried styling table borders with

```yaml
style:
  table:
    border: solid 1pt $brand-color-tertiary
```

but that only affects the outer table frame, not inner cell/column/row borders.

I know there are many permutations of `@frame` settings that would be tough to map to YAML/JSON, just wondering if there's a good way to set all table borders at once.
