### ISSUE TITLE
PDF `--theme`: Borders on empty headers/footers

### ISSUE THREAD

**Issue by infotexture** [jelovirt/pdf-generator#69]
When borders are applied to running headers/footers:

```yaml
header:
  border-after: solid 1pt $brand-color-inverse
footer:
  border-before: solid 1pt $brand-color-inverse
```

The borders are drawn on **every** page, even those that do not contain header/footer content — like the title page, empty pages, index, etc.

Since the content is empty, the region height is different from the populated headers/footers, so the border lines appear in different places than they do on pages with real headers/footers.

Not sure how easy this is to change, but would be elegant if borders were only drawn on pages that actually contain header/footer content.
